"""Init

<<<<<<<< HEAD:migrations/versions/26b5a3153361_init.py
Revision ID: 26b5a3153361
Revises: 
Create Date: 2024-02-19 19:28:22.858439
========
Revision ID: decdba2d944d
Revises: 
Create Date: 2024-02-20 11:26:54.022149
>>>>>>>> 8f27200f20c4e4e8454ffcc6a400f233c2c89cc2:migrations/versions/decdba2d944d_init.py

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/26b5a3153361_init.py
revision = '26b5a3153361'
========
revision = 'decdba2d944d'
>>>>>>>> 8f27200f20c4e4e8454ffcc6a400f233c2c89cc2:migrations/versions/decdba2d944d_init.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<<< HEAD:migrations/versions/26b5a3153361_init.py
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('publicationName', sa.String(), nullable=False),
    sa.Column('issn', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('journalRanking_value', sa.Float(), nullable=True),
    sa.Column('journalRanking_type', sa.String(), nullable=True),
    sa.Column('journalRanking_year', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('publicationDate', sa.String(), nullable=False),
    sa.Column('url', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.Column('publicationID', sa.String(), nullable=False),
    sa.Column('is_vak', sa.Boolean(), nullable=False),
    sa.Column('is_WoS', sa.Boolean(), nullable=False),
    sa.Column('is_Scopus', sa.Boolean(), nullable=False),
    sa.Column('is_RINC', sa.Boolean(), nullable=False),
    sa.Column('val_WoS', sa.Integer(), nullable=True),
    sa.Column('val_Scopus', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('attachments', sa.String(), nullable=True),
========
    op.create_table('patents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('creators', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
>>>>>>>> 8f27200f20c4e4e8454ffcc6a400f233c2c89cc2:migrations/versions/decdba2d944d_init.py
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presentations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('conference', sa.String(), nullable=False),
    sa.Column('publicationDate', sa.String(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('kind', sa.Enum('ORAL', 'POSTER', 'INVITED', 'PLENAR', name='kind', native_enum=False), nullable=False),
    sa.Column('presentationid', sa.String(), nullable=False),
    sa.Column('confid', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('creators', sa.ARRAY(sa.Integer()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('presentationid')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('irid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('irid')
    )
<<<<<<<< HEAD:migrations/versions/26b5a3153361_init.py
    op.create_table('articles_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presentations_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['presentations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
========
>>>>>>>> 8f27200f20c4e4e8454ffcc6a400f233c2c89cc2:migrations/versions/decdba2d944d_init.py
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<<< HEAD:migrations/versions/26b5a3153361_init.py
    op.drop_table('presentations_users')
    op.drop_table('articles_users')
    op.drop_table('users')
    op.drop_table('presentations')
    op.drop_table('articles')
========
    op.drop_table('users')
    op.drop_table('presentations')
    op.drop_table('patents')
>>>>>>>> 8f27200f20c4e4e8454ffcc6a400f233c2c89cc2:migrations/versions/decdba2d944d_init.py
    # ### end Alembic commands ###